- name: DevTools
  hosts: localhost
  connection: local

  tasks:
  - name: Install neovim
    ansible.builtin.package:
      name:
      - neovim
      state: present

  - name: Install rust unix replacements
    ansible.builtin.package:
      name:
      - erdtree
      - fzf
      - fd
      - eza
      - zoxide
      state: present

  - name: Install zellij
    ansible.builtin.package:
      name:
      - zellij
      state: present

  - name: Install tmux
    ansible.builtin.package:
      name:
      - tmux
      state: present

  - name: Install just
    ansible.builtin.package:
      name:
      - just
      state: present

  - name: Install pre-commit
    ansible.builtin.package:
      name:
      - pre-commit
      state: present

  - name: Install charmbracelet tools
    ansible.builtin.package:
      name:
      - glow
      - gum
      state: present

  - name: Install stow
    ansible.builtin.package:
      name:
      - stow
      state: present

  - name: Install llvm
    ansible.builtin.package:
      name:
      - llvm
      state: present

  - name: Install llvd
    when:
    - ansible_facts['distribution'] == "Archlinux"
    ansible.builtin.package:
      name:
      - lldb
      state: present
